#
#APP TIER simple app, with no DB backend 
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-v1
  namespace: myapp
  labels:
    app: myapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
      - name: myapp-v1
        image: docker.io/giriraj789/ngapp:v1 
        ports:
        - containerPort: 80
          name: version-1-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-v2
  namespace: myapp
  labels:
    app: myapp
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: v2
  template:
    metadata:
      labels:
        app: myapp
        version: v2
    spec:
      containers:
      - name: myapp-v1
        image: docker.io/giriraj789/ngapp:v2
        ports:
        - containerPort: 80
          name: version-2-port
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: myapp-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
