#
#APP TIER simple app, with no DB backend 
#
---
apiVersion: apps/v1
kind: Namespace
metadata:
   name: app-tier
   label:
     istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier-deployment-v1
  namespace: app-tier
  labels:
    app: app-tier
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tier
      version: v1
  template:
    metadata:
      labels:
        app: app-tier
        version: v1
    spec:
      containers:
      - name: app-tier-v1
        image: docker.io/giriraj789/ngapp:v1 
        ports:
        - containerPort: 80
          name: version-1-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier-deployment-v2
  namespace: app-tier
  labels:
    app: app-tier
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tier
      version: v2
  template:
    metadata:
      labels:
        app: app-tier
        version: v2
    spec:
      containers:
      - name: app-tier-v2
        image: docker.io/giriraj789/ngapp:v2
        ports:
        - containerPort: 80
          name: version-2-port
---
apiVersion: v1
kind: Service
metadata:
  name: app-tier-svc
  namespace: app-tier
spec:
  selector:
    app: app-tier
  ports:
    - name: app-tier-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
