apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: giriraj789/2in1:v1
        ports:
        - containerPort: 8081
          name: http-servera
        - containerPort: 8082
          name: http-serverb
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - name: http-servera
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: http-serverb
      port: 8082
      targetPort: 8082
      protocol: TCP         
