apiVersion: v1
kind: Pod
metadata:
  labels:
   app.kubernetes.io/name: nc1
   app.kubernetes.io/instance: nc1 
  name: nc1
  annotations:
     k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: nc1
    image: giriraj789/tester:v1
