apiVersion: v1
kind: Pod
metadata:
  labels:
   app.kubernetes.io/name: nc1
   app.kubernetes.io/instance: nc1 
  name: nc1
  annotations:
    robin.io/networks: '[{"ippool": "ng-bond-sriov-en134", "interface_name": "ram"}]'
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nc1
    image: giriraj789/tester:v1
