apiVersion: v1
kind: Namespace
metadata:
  name: test-tier
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-tier
  namespace: test-tier
  labels:
    app: test-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-tier
  template:
    metadata:
      labels:
        app: test-tier
    spec:
      containers:
      - name: test-tier
        image: giriraj789/tester:v1
