apiVersion: v1
kind: Namespace
metadata:
  name: web-tier
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: web-tier
data:
  default.conf: |
   server {
     listen 80;
     location / {
        proxy_pass http://app-tier-svc.app-tier.svc.cluster.local;
               }
          }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-tier-deployment
  namespace: web-tier
spec:
  selector:
    matchLabels:
      app: web-tier
  replicas: 1
  template:
    metadata:
      labels:
        app: web-tier
    spec:
      containers:
      - name: web-tier
        image: nginx
        ports:
        - containerPort: 80
          name: http-web-tier 
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: default.conf
              path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: web-tier-svc
  namespace: web-tier
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: web-tier
